apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
  namespace: adl-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
