apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
  namespace: adl-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /data/auth

