apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-config
  namespace: adl-dev
data:
  hazelcast.yaml: |-
     hazelcast:
      group:
        name: adl-dev
        password: YXxNONejhNmLqw
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            namespace: adl-dev
            service-name: hazelcast
      rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
      management-center:
        enabled: true
        url: http://172.20.103.187:8080/hazelcast-mancenter
