apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
  namespace: adl-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: hazelcast/hazelcast:3.12.12
        ports:
        - containerPort: 5701
          name: hazelcast
        volumeMounts:
        - name: hazelcast-config
          mountPath: /opt/hazelcast/hazelcast.yaml
          subPath: hazelcast.yaml
      volumes:
      - name: hazelcast-config
        configMap:
          name: hazelcast-config

