apiVersion: v1
kind: PersistentVolume
metadata:
  name: hazelcast-pv
  namespace: adl-dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /data/hazelcast
