apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hazelcast-pvc
  namespace: adl-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2

