apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  namespace: adl-dev
spec:
  ports:
  - name: hazelcast
    port: 5701
    protocol: TCP
    targetPort: hazelcast
  selector:
    app: hazelcast
