apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: adl-dev
  labels:
    name: gateway
spec:
  selector:
    app: gateway
  ports:
  - name: http
    protocol: TCP
    port: 50000


